<?php

namespace App\Services\Tenants;

use Illuminate\Http\Request;
use App\Models\Tenants\Event;
use App\Http\Requests\StoreEvent;
use App\Http\Requests\UpdateEvent;

class EventService
{
    /**
     * This is used during the creation of a new event.
     *
     * @param StoreEvent $request
     * @return Event
     */
    public function storeEvent(StoreEvent $request)
    {
        $event = new Event();
        $event->title = $request->title;
        $event->description = $request->description;
        $event->start_date = $request->start_date;
        $event->start_time = $request->start_time;
        $event->end_date = $request->end_date;
        $event->end_time = $request->end_time;
        $event->banner_image_link = $request->banner_image_link;

        $event->save();

        return $event;
    }

    /**
     * This is used during the update of an existing event.
     *
     * @param UpdateEvent $request
     * @param $slug
     * @return mixed
     */
    public function updateEvent(UpdateEvent $request, $slug)
    {
        $event = $this->getBySlug($slug);

        $event->title = $request->title;
        $event->slug = null; // Emptied to null in order for a new slug to be generated by sluggable
        $event->description = $request->description;
        $event->start_date = $request->start_date;
        $event->start_time = $request->start_time;
        $event->end_date = $request->end_date;
        $event->end_time = $request->end_time;
        $event->banner_image_link = $request->banner_image_link;

        $event->save();

        return $event;
    }

    /**
     * This is used during the destruction of an existing event.
     *
     * @param Request $request
     * @param $slug
     */
    public function destroyEvent(Request $request, $slug)
    {
        $event = $this->getBySlug($slug);

        $this->delete($event);
    }

    /**
     * This returns a collection of all the events.
     *
     * @return Event[]|\Illuminate\Database\Eloquent\Collection
     */
    public function getAll()
    {
        return Event::all();
    }

    /**
     * This is used to grab an event based on slug.
     *
     * @param $slug
     * @return mixed
     */
    public function getBySlug($slug)
    {
        return Event::whereSlug($slug)->first();
    }

    /**
     * Delete the given tenant.
     *
     * @param Event $event
     * @throws \Exception
     */
    public function delete(Event $event)
    {
        $event->delete();
    }
}
